name: Syntax Tests

on:
  push:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - '.github/workflows/syntax.yml'
      - '**.sublime-syntax'
      - '**/syntax_test*'
      - '**.tmPreferences'

jobs:
  main:
    name: Syntax Tests (${{ matrix.build }})
    strategy:
      matrix:
        include:
          - build: 3211
          - build: 4073
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
     - name: Install lbzip2
        run: sudo apt-get update && sudo apt-get install -y lbzip2
      - uses: SublimeText/syntax-test-action@v1
        with:
          build: ${{ matrix.build }}
          package_name: Fennel
          package_root: sublime-text-fennel
